### ISSUE TITLE
kmbarry1 review comments

### ISSUE THREAD

**Issue by kmbarry1** [makerdao/vote-delegate#2]
We usually name `mappings` after their values, not their keys, and we usually use the singular, so I'd suggest renaming `delegators` to `stake` or something similar.

Other than that...just the ongoing concern about delegation being potentially everlasting, which #1 is addressing.

**Comment by gbalabasquer** [comment]
This was fixed in this PR: https://github.com/makerdao/vote-delegate/pull/3
